### ISSUE TITLE
Please explain the difference with MongoConnector

### ISSUE THREAD

**Issue by pcav** [adrianaksan/qgis-mongodb-plugin#1]
See http://plugins.qgis.org/plugins/MongoConnector/
An user should be able, by reading the About, to understand why using one of the two.

**Comment by adrianaksan** [comment]
Not a problem. I've added an improved "About". Hopefully this will be enough.

**Comment by pcav** [comment]
I still do  not see the updated About on the website http://plugins.qgis.org/plugins/qgis-mongodb-loader/

**Comment by adrianaksan** [comment]
Alright. I think I've managed to upload the new "About". Can I include a \n or a <br> in the text somehow?
