### ISSUE TITLE
Allow to set a query

### ISSUE THREAD

**Issue by corinis** [adrianaksan/qgis-mongodb-plugin#10]
Currently the plugin simply gets ALL data in a collection.

When working with bigger datasets it might be good to add a text-area where you can set a query which is then added when getting the data (mabye also do a count in the dialog to see how many results would come back using the given query).

Sample:

```
{ 
   "properties.type": "street"
}
```

and this would then create a layer with the given query.

**Comment by adrianaksan** [comment]
Thanks for the suggestion. I haven't looked at this project for a while. Maybe it's time for some updates :)

**Comment by corinis** [comment]
cool. I just thought it would be even better - in addition to do custom queries - to have a default query that simply allows a geoquery i.e. you specify a point and a radius and this will will generate a "near" query in mongodb - that way you can take a closer look at a specific are instead of loading all data.

Its just a usability thing, but when working with geodata you quickly reach a LOT of entries, so allowing a limit would allow much faster use for quick data analysis
