### ISSUE TITLE
Shapefile export relevant ?

### ISSUE THREAD

**Issue by geopan** [adrianaksan/qgis-mongodb-plugin#11]
@adrianaksan,

I was wondering if it really needs to export the layer as shapefile. The format breaks down the attributes names. Exporting data in a different format can be easily done afterward once the layer is in memory. It would allow us to keep original attributes.

Cheers

G

**Comment by adrianaksan** [comment]
Thanks geopan, I will add this functionality with the next version. Loading the layers to memory is probably a more elegant solution.
