### ISSUE TITLE
Data not visible

### ISSUE THREAD

**Issue by VasiliosKalogirou** [adrianaksan/qgis-mongodb-plugin#12]
Hi Adrian, 
I am having the same issue as NILUFER and HAFF112 in https://qgismongodb.wordpress.com/2015/07/23/loading-layers/comment-page-1/#comment-20 
where I load a collection successfully but I can't see any data. Here's a sample of my data:

{ "type": "Feature", "properties": { "id": 1.0, "osm_id": 4757536.0, "name": null, "type": "taxiway" }, "geometry": { "type": "LineString", "coordinates": [ [ 33.284198244997214, 35.144497784256515 ], [ 33.282674834095417, 35.143663533433646 ] ] } }
{ "type": "Feature", "properties": { "id": 2.0, "osm_id": 5212814.0, "name": null, "type": "runway" }, "geometry": { "type": "LineString", "coordinates": [ [ 33.32026431706737, 35.11236466879344 ], [ 33.320523234056395, 35.110997748023919 ] ] } }

Can you please help with this?

Thanks,
Vasilios

**Comment by adrianaksan** [comment]
This issue has now been resolved. Please download the latest version. Cheers.
