### ISSUE TITLE
Attribute names

### ISSUE THREAD

**Issue by VasiliosKalogirou** [adrianaksan/qgis-mongodb-plugin#13]
Hi Adrian,

The plugin works perfectly for me at the moment in terms of loading the geometry of the features but it does not load the attribute names properly. I was wondering if it's possible to fix this and instead of loading "properti_1", "properti_2", etc, the plugin loads the actual attribute name, i.e. "name", "city", etc.

Cheers,
Vasilios

**Comment by adrianaksan** [comment]
Thanks VasiliosKalogirou, I will look into this and resolve ASAP.
